language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
- awesome_bot README.md --allow-dupe --allow-redirect --white-list it-ebooks.info,bento.io,clipmenu.com
notifications:
  email: false
